import { 
  SatelliteData, ConflictEvent, AircraftData, VesselData, 
  EarthquakeData, WeatherData, CyberThreat, NewsItem, 
  RiskAssessment, SystemStatus, Alert 
} from '@/types';

export const mockSatellites: SatelliteData[] = [
  {
    id: 'iss-001',
    name: 'ISS (ZARYA)',
    type: 'ISS',
    latitude: 51.6416,
    longitude: -0.1276,
    altitude: 408,
    velocity: 27600,
    orbitPeriod: 92.68,
    inclination: 51.64,
    nextPass: '2026-06-16T14:30:00Z',
    status: 'active',
  },
  {
    id: 'starlink-1045',
    name: 'STARLINK-1045',
    type: 'Starlink',
    latitude: 53.2158,
    longitude: 15.7421,
    altitude: 550,
    velocity: 27300,
    orbitPeriod: 95.0,
    inclination: 53.0,
    nextPass: '2026-06-16T16:15:00Z',
    status: 'active',
  },
  {
    id: 'nrol-22',
    name: 'USA-223 (NROL-22)',
    type: 'Spy',
    latitude: 63.4,
    longitude: -120.5,
    altitude: 35786,
    velocity: 3074,
    orbitPeriod: 1436.1,
    inclination: 0.0,
    nextPass: 'N/A - GEO',
    status: 'active',
  },
  {
    id: 'sbirs-geo-2',
    name: 'SBIRS GEO-2',
    type: 'Military',
    latitude: 0.0,
    longitude: -70.0,
    altitude: 35786,
    velocity: 3074,
    orbitPeriod: 1436.1,
    inclination: 0.0,
    nextPass: 'N/A - GEO',
    status: 'active',
  },
  {
    id: 'goes-18',
    name: 'GOES-18',
    type: 'Weather',
    latitude: 0.0,
    longitude: -137.0,
    altitude: 35786,
    velocity: 3074,
    orbitPeriod: 1436.1,
    inclination: 0.0,
    nextPass: 'N/A - GEO',
    status: 'active',
  },
  {
    id: 'gps-3f-1',
    name: 'GPS III SV01',
    type: 'Navigation',
    latitude: 55.0,
    longitude: -80.0,
    altitude: 20200,
    velocity: 3880,
    orbitPeriod: 718.0,
    inclination: 55.0,
    nextPass: '2026-06-16T18:45:00Z',
    status: 'active',
  },
];

export const mockConflicts: ConflictEvent[] = [
  {
    id: 'conflict-001',
    location: 'Kyiv, Ukraine',
    coordinates: [50.4501, 30.5234],
    type: 'armed_conflict',
    severity: 85,
    casualties: 1247,
    timestamp: '2026-06-16T08:30:00Z',
    description: 'Intense artillery exchange reported in eastern districts. Air raid sirens active.',
    source: 'ACLED',
    region: 'Ukraine',
  },
  {
    id: 'conflict-002',
    location: 'Gaza Strip',
    coordinates: [31.5017, 34.4668],
    type: 'armed_conflict',
    severity: 92,
    casualties: 3420,
    timestamp: '2026-06-16T06:15:00Z',
    description: 'Major military operation underway. Civilian infrastructure heavily damaged.',
    source: 'GDELT',
    region: 'Middle East',
  },
  {
    id: 'conflict-003',
    location: 'Taiwan Strait',
    coordinates: [23.5, 121.0],
    type: 'border_dispute',
    severity: 78,
    casualties: 0,
    timestamp: '2026-06-16T10:00:00Z',
    description: 'Naval exercises detected. Multiple warships and aircraft in contested zone.',
    source: 'Crisis24',
    region: 'South China Sea',
  },
  {
    id: 'conflict-004',
    location: 'Khartoum, Sudan',
    coordinates: [15.5007, 32.5599],
    type: 'civil_unrest',
    severity: 72,
    casualties: 856,
    timestamp: '2026-06-16T04:20:00Z',
    description: 'Renewed clashes between rival factions. Humanitarian corridors blocked.',
    source: 'ReliefWeb',
    region: 'Africa',
  },
  {
    id: 'conflict-005',
    location: 'Arctic Ocean',
    coordinates: [75.0, -40.0],
    type: 'border_dispute',
    severity: 45,
    casualties: 0,
    timestamp: '2026-06-16T12:00:00Z',
    description: 'Increased naval patrols detected. Icebreaker activity above normal levels.',
    source: 'OSINT',
    region: 'Arctic',
  },
  {
    id: 'conflict-006',
    location: 'Tehran, Iran',
    coordinates: [35.6892, 51.3890],
    type: 'cyber_attack',
    severity: 65,
    casualties: 0,
    timestamp: '2026-06-16T09:45:00Z',
    description: 'Critical infrastructure targeted. Power grid disruptions reported.',
    source: 'AlienVault OTX',
    region: 'Middle East',
  },
];

export const mockAircraft: AircraftData[] = [
  {
    id: 'ac-001',
    callsign: 'NOBLE01',
    type: 'E-3 Sentry',
    category: 'AWACS',
    latitude: 51.2,
    longitude: 7.1,
    altitude: 32000,
    speed: 450,
    heading: 270,
    country: 'NATO',
    origin: 'Geilenkirchen AB',
    destination: 'Eastern Poland',
    squawk: '7700',
  },
  {
    id: 'ac-002',
    callsign: 'TANKER42',
    type: 'KC-135',
    category: 'Tanker',
    latitude: 48.5,
    longitude: 11.0,
    altitude: 28000,
    speed: 480,
    heading: 90,
    country: 'USA',
    origin: 'RAF Mildenhall',
    destination: 'Baltic Sea',
    squawk: '3452',
  },
  {
    id: 'ac-003',
    callsign: 'GHOST71',
    type: 'RQ-4 Global Hawk',
    category: 'ISR',
    latitude: 35.2,
    longitude: 139.5,
    altitude: 55000,
    speed: 350,
    heading: 180,
    country: 'USA',
    origin: 'Beale AFB',
    destination: 'Pacific Ocean',
    squawk: '7200',
  },
  {
    id: 'ac-004',
    callsign: 'REAPER22',
    type: 'MQ-9 Reaper',
    category: 'Drone',
    latitude: 33.3,
    longitude: 44.4,
    altitude: 25000,
    speed: 200,
    heading: 45,
    country: 'USA',
    origin: 'Ali Al Salem',
    destination: 'Iraq Border',
    squawk: '1000',
  },
  {
    id: 'ac-005',
    callsign: 'FORTRESS',
    type: 'B-52H',
    category: 'Military',
    latitude: 65.0,
    longitude: -18.0,
    altitude: 35000,
    speed: 520,
    heading: 315,
    country: 'USA',
    origin: 'Barksdale AFB',
    destination: 'Arctic Circle',
    squawk: '4400',
  },
];

export const mockVessels: VesselData[] = [
  {
    id: 'vsl-001',
    name: 'USS GERALD R. FORD',
    type: 'Aircraft Carrier',
    latitude: 36.9,
    longitude: -75.3,
    speed: 18,
    heading: 90,
    flag: 'USA',
    destination: 'Mediterranean Sea',
    status: 'underway',
    mmsi: '368926000',
  },
  {
    id: 'vsl-002',
    name: 'USS ARLEIGH BURKE',
    type: 'Destroyer',
    latitude: 35.2,
    longitude: 139.7,
    speed: 25,
    heading: 180,
    flag: 'USA',
    destination: 'South China Sea',
    status: 'underway',
    mmsi: '369999999',
  },
  {
    id: 'vsl-003',
    name: 'USS OHIO',
    type: 'Submarine',
    latitude: 38.0,
    longitude: -125.0,
    speed: 12,
    heading: 270,
    flag: 'USA',
    destination: 'Pacific Ocean',
    status: 'underway',
    mmsi: 'UNKNOWN',
  },
  {
    id: 'vsl-004',
    name: 'EVER GIVEN',
    type: 'Cargo',
    latitude: 30.0,
    longitude: 32.5,
    speed: 15,
    heading: 0,
    flag: 'PANAMA',
    destination: 'Suez Canal',
    status: 'underway',
    mmsi: '353136000',
  },
  {
    id: 'vsl-005',
    name: 'LNG SAKURA',
    type: 'LNG',
    latitude: 26.0,
    longitude: 56.0,
    speed: 14,
    heading: 45,
    flag: 'QATAR',
    destination: 'Strait of Hormuz',
    status: 'underway',
    mmsi: '466500000',
  },
];

export const mockEarthquakes: EarthquakeData[] = [
  {
    id: 'eq-001',
    magnitude: 6.2,
    location: 'Near Coast of Chile',
    coordinates: [-35.5, -72.5],
    depth: 45,
    timestamp: '2026-06-16T07:30:00Z',
    alert: 'orange',
  },
  {
    id: 'eq-002',
    magnitude: 4.8,
    location: 'Southern California',
    coordinates: [34.0, -118.5],
    depth: 12,
    timestamp: '2026-06-16T05:15:00Z',
    alert: 'yellow',
  },
  {
    id: 'eq-003',
    magnitude: 7.1,
    location: 'Offshore Japan',
    coordinates: [38.0, 142.0],
    depth: 35,
    timestamp: '2026-06-16T03:00:00Z',
    alert: 'red',
  },
  {
    id: 'eq-004',
    magnitude: 3.2,
    location: 'Iceland',
    coordinates: [64.0, -19.0],
    depth: 8,
    timestamp: '2026-06-16T11:20:00Z',
    alert: 'green',
  },
];

export const mockWeather: WeatherData[] = [
  {
    location: 'North Atlantic',
    coordinates: [45.0, -30.0],
    temperature: 12,
    humidity: 78,
    windSpeed: 45,
    windDirection: 270,
    pressure: 998,
    condition: 'Storm',
    visibility: 5,
  },
  {
    location: 'Arabian Sea',
    coordinates: [20.0, 65.0],
    temperature: 34,
    humidity: 65,
    windSpeed: 25,
    windDirection: 180,
    pressure: 1012,
    condition: 'Clear',
    visibility: 20,
  },
  {
    location: 'Western Pacific',
    coordinates: [15.0, 130.0],
    temperature: 28,
    humidity: 85,
    windSpeed: 120,
    windDirection: 90,
    pressure: 950,
    condition: 'Typhoon',
    visibility: 2,
  },
];

export const mockCyberThreats: CyberThreat[] = [
  {
    id: 'cyber-001',
    type: 'DDoS',
    origin: 'Russia',
    target: 'Ukrainian Government',
    severity: 75,
    timestamp: '2026-06-16T08:00:00Z',
    description: 'Large-scale DDoS attack targeting critical infrastructure.',
    indicators: ['185.220.101.0/24', '194.32.107.88', 'TOR exit nodes'],
  },
  {
    id: 'cyber-002',
    type: 'Ransomware',
    origin: 'Unknown',
    target: 'European Healthcare',
    severity: 82,
    timestamp: '2026-06-16T06:30:00Z',
    description: 'LockBit variant detected. Multiple hospitals affected.',
    indicators: ['lockbit-3.0.exe', 'ransom-note.txt', 'bitcoin-wallet'],
  },
  {
    id: 'cyber-003',
    type: 'NationState',
    origin: 'China',
    target: 'US Defense Contractor',
    severity: 88,
    timestamp: '2026-06-16T04:00:00Z',
    description: 'APT41 activity detected. Supply chain compromise suspected.',
    indicators: ['ShadowPad', 'Cobalt Strike', 'Living off the land'],
  },
  {
    id: 'cyber-004',
    type: 'Malware',
    origin: 'Iran',
    target: 'Middle East Energy',
    severity: 65,
    timestamp: '2026-06-16T09:15:00Z',
    description: 'New wiper malware targeting SCADA systems.',
    indicators: ['wiper.exe', 'SCADA-target', 'Iran-APT'],
  },
];

export const mockNews: NewsItem[] = [
  {
    id: 'news-001',
    title: 'NATO Deploys Additional Forces to Eastern Flank',
    source: 'Reuters',
    timestamp: '2026-06-16T10:30:00Z',
    category: 'Military',
    sentiment: 'negative',
    summary: 'NATO announces deployment of 10,000 additional troops to Poland and Baltic states amid rising tensions.',
    url: '#',
  },
  {
    id: 'news-002',
    title: 'China Conducts Military Exercises Near Taiwan',
    source: 'AP News',
    timestamp: '2026-06-16T09:00:00Z',
    category: 'Geopolitics',
    sentiment: 'negative',
    summary: 'PLA Navy and Air Force conduct joint exercises in Taiwan Strait. US monitoring closely.',
    url: '#',
  },
  {
    id: 'news-003',
    title: 'New Satellite Imagery Shows Activity at Iranian Nuclear Site',
    source: 'Defense News',
    timestamp: '2026-06-16T07:45:00Z',
    category: 'Intelligence',
    sentiment: 'negative',
    summary: 'Sentinel-2 imagery reveals increased construction activity at Fordow facility.',
    url: '#',
  },
  {
    id: 'news-004',
    title: 'Global Supply Chain Disruptions Ease Slightly',
    source: 'BBC',
    timestamp: '2026-06-16T06:00:00Z',
    category: 'Economy',
    sentiment: 'positive',
    summary: 'Shipping costs decline 15% as Red Sea transit resumes partial operations.',
    url: '#',
  },
  {
    id: 'news-005',
    title: 'Russia-Ukraine Energy Infrastructure Attacks Intensify',
    source: 'Al Jazeera',
    timestamp: '2026-06-16T05:30:00Z',
    category: 'Conflict',
    sentiment: 'negative',
    summary: 'Both sides target energy infrastructure. Blackouts reported in multiple regions.',
    url: '#',
  },
];

export const mockRiskAssessments: RiskAssessment[] = [
  {
    country: 'Ukraine',
    overallScore: 92,
    politicalRisk: 95,
    economicRisk: 88,
    militaryRisk: 98,
    cyberRisk: 85,
    terrorismRisk: 72,
    trend: 'increasing',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
  {
    country: 'Taiwan',
    overallScore: 78,
    politicalRisk: 85,
    economicRisk: 65,
    militaryRisk: 90,
    cyberRisk: 80,
    terrorismRisk: 30,
    trend: 'increasing',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
  {
    country: 'Iran',
    overallScore: 75,
    politicalRisk: 80,
    economicRisk: 70,
    militaryRisk: 82,
    cyberRisk: 78,
    terrorismRisk: 85,
    trend: 'stable',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
  {
    country: 'Russia',
    overallScore: 82,
    politicalRisk: 90,
    economicRisk: 75,
    militaryRisk: 88,
    cyberRisk: 92,
    terrorismRisk: 65,
    trend: 'stable',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
  {
    country: 'China',
    overallScore: 68,
    politicalRisk: 75,
    economicRisk: 60,
    militaryRisk: 72,
    cyberRisk: 85,
    terrorismRisk: 45,
    trend: 'increasing',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
  {
    country: 'Israel',
    overallScore: 85,
    politicalRisk: 88,
    economicRisk: 70,
    militaryRisk: 92,
    cyberRisk: 80,
    terrorismRisk: 90,
    trend: 'increasing',
    lastUpdated: '2026-06-16T12:00:00Z',
  },
];

export const mockSystemStatus: SystemStatus[] = [
  { module: 'Satellite Feed', status: 'online', latency: 45, uptime: '99.98%', lastUpdate: '2026-06-16T11:04:00Z' },
  { module: 'ACLED Feed', status: 'online', latency: 120, uptime: '99.95%', lastUpdate: '2026-06-16T11:03:00Z' },
  { module: 'GDELT Feed', status: 'online', latency: 85, uptime: '99.92%', lastUpdate: '2026-06-16T11:02:00Z' },
  { module: 'OpenSky Network', status: 'online', latency: 200, uptime: '99.87%', lastUpdate: '2026-06-16T11:01:00Z' },
  { module: 'AIS Stream', status: 'degraded', latency: 500, uptime: '98.45%', lastUpdate: '2026-06-16T11:00:00Z' },
  { module: 'USGS Earthquake', status: 'online', latency: 150, uptime: '99.99%', lastUpdate: '2026-06-16T11:04:00Z' },
  { module: 'NASA FIRMS', status: 'online', latency: 300, uptime: '99.90%', lastUpdate: '2026-06-16T11:03:00Z' },
  { module: 'AlienVault OTX', status: 'online', latency: 180, uptime: '99.85%', lastUpdate: '2026-06-16T11:02:00Z' },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    level: 'red',
    title: 'CRITICAL: Major Escalation in Gaza',
    description: 'Large-scale military operation detected. Civilian casualties reported.',
    timestamp: '2026-06-16T06:15:00Z',
    region: 'Middle East',
    acknowledged: false,
  },
  {
    id: 'alert-002',
    level: 'orange',
    title: 'HIGH: Naval Activity in Taiwan Strait',
    description: 'Multiple PLA warships and aircraft detected in ADIZ.',
    timestamp: '2026-06-16T10:00:00Z',
    region: 'South China Sea',
    acknowledged: false,
  },
  {
    id: 'alert-003',
    level: 'orange',
    title: 'HIGH: Earthquake M7.1 Japan',
    description: 'Tsunami warning issued. Nuclear facilities on alert.',
    timestamp: '2026-06-16T03:00:00Z',
    region: 'Pacific',
    acknowledged: true,
  },
  {
    id: 'alert-004',
    level: 'yellow',
    title: 'ELEVATED: Cyber Attack on EU Healthcare',
    description: 'Ransomware campaign affecting multiple hospitals.',
    timestamp: '2026-06-16T06:30:00Z',
    region: 'Europe',
    acknowledged: false,
  },
  {
    id: 'alert-005',
    level: 'yellow',
    title: 'ELEVATED: Arctic Naval Patrols',
    description: 'Increased Russian icebreaker and submarine activity detected.',
    timestamp: '2026-06-16T12:00:00Z',
    region: 'Arctic',
    acknowledged: false,
  },
];
